# Change these first
owner: youknowblom # Your GitHub organization or username, where this repository lives
repo: d-sektionen-upptime # The name of this repository
delay: 1000 # Add 1s of delay to prevent tripping DDOS protection

sites:
  - name: Medlemstjänster - Backend
    url: https://backend.d-sektionen.se/tools/status
  - name: Medlemstjänster - Frontend
    url: https://medlem.d-sektionen.se
  - name: Hemsida
    url: https://d-sektionen.se
  - name: Lysator
    url: lysator.liu.se

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /d-sektionen-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: D-sektionen - Upptime
  introTitle: "Status över D-sektionens tjänster."
  introMessage: "**Ifall Lysator är nere är troligen våra tjänster också det. Isåfall ligger problemet hos dem.**"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
